### ISSUE TITLE
Add .idea folder to Git

### ISSUE THREAD

**Issue by dhardtke** [28Smiles/jdbi-modules#1]
I presume it would be a good idea to add the .idea folder to the Git repository, see [How to manage projects under version control](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems)

Also, a .gitignore should be added.

**Comment by 28Smiles** [comment]
In my opinion no .idea folder is needed, but I will add a gitignore.
