### ISSUE TITLE
Sorting JOINed beans

### ISSUE THREAD

**Issue by dhardtke** [28Smiles/jdbi-modules#23]
Hey there,

I was wondering if there was a possibility to sort the beans that I joined and mapped.

I figured `sortOrder()` wouldn't work since I am having multiple JOINs and multiple beans that might interfere with each other, so: Is there an option to sort beans in user code after mapping?

**Comment by 28Smiles** [comment]
How about using a sorted list as container?

**Comment by dhardtke** [comment]
Well, I am mostly using ArrayLists since I only want to sort the items when loading. Also, using a SortedSet is not viable.Am 08.11.2018 09:52 schrieb 28Smiles <notifications@github.com>:How about using a sorted list as container?
